# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PlrpadcLLGJO3EJLWdWXqWkLYNvGBuvk
"""

!pip install experta

!pip install --upgrade frozendict experta

!pip install --upgrade frozendict

from experta import *

class Diagnosis(KnowledgeEngine):

    @Rule(Fact(cough=True) & Fact(fever=True) & Fact(fatigue=True) & Fact(breathing_difficulty=False))
    def flu(self):
        print("Diagnosis: You may have the Flu.")

    @Rule(Fact(cough=True) & Fact(fever=True) & Fact(breathing_difficulty=True) & Fact(fatigue=False))
    def pneumonia(self):
        print("Diagnosis: You may have Pneumonia.")

    @Rule(Fact(sneezing=True) & Fact(runny_nose=True) & Fact(cough=False) & Fact(fever=False))
    def cold(self):
        print("Diagnosis: You may have a Common Cold.")

    @Rule(Fact(sore_throat=True) & Fact(fever=True) & Fact(cough=False))
    def throat_infection(self):
        print("Diagnosis: You may have a Throat Infection.")

    @Rule(Fact(cough=True) & Fact(fever=True) & Fact(breathing_difficulty=True) & Fact(fatigue=True))
    def covid(self):
        print("Diagnosis: You may have COVID-19.")

    @Rule(Fact(sneezing=True) & Fact(runny_nose=True) & Fact(fever=False) & Fact(cough=True))
    def Nyeri(self):
        print("Diagnosis: You may have an Nyeri.")

    @Rule(Fact(cough=True) & Fact(fatigue=True) & Fact(fever=False) & Fact(breathing_difficulty=True))
    def Anemia(self):
        print("Diagnosis: You may have Anemia.")

    @Rule(Fact(sore_throat=False) & Fact(fatigue=False) & Fact(runny_nose=True) & Fact(sneezing=False) & Fact(cough=False))
    def Bentol(self):
        print("Diagnosis: You may have Bentol.")

    @Rule(Fact(cough=False) & Fact(fever=False) & Fact(fatigue=False) & Fact(breathing_difficulty=False) &
          Fact(sneezing=False) & Fact(runny_nose=False) & Fact(sore_throat=False))
    def healthy(self):
        print("Diagnosis: You seem to be healthy.")

def get_input():
    """Helper function to get user input as boolean (yes/no)."""
    def ask_question(question):
        return input(question + " (yes/no): ").strip().lower() == "yes"

    return {
        "cough": ask_question("Do you have a cough?"),
        "fever": ask_question("Do you have a fever?"),
        "fatigue": ask_question("Do you feel fatigued?"),
        "breathing_difficulty": ask_question("Do you have breathing difficulties?"),
        "sneezing": ask_question("Are you sneezing?"),
        "runny_nose": ask_question("Do you have a runny nose?"),
        "sore_throat": ask_question("Do you have a sore throat?")
    }

# Running the Expert System
if __name__ == "__main__":
    symptoms = get_input()
    engine = Diagnosis()
    engine.reset()  # Reset the knowledge engine

    for symptom, present in symptoms.items():
        engine.declare(Fact(**{symptom: present}))  # Declare facts

    engine.run()  # Run the inference engine